In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle

# Load the California Housing dataset
california = fetch_california_housing()

C:\Users\Lenovo\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
california.data.shape

(20640, 8)

In [5]:
california.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [4]:
type(california)

sklearn.utils._bunch.Bunch

In [6]:
california["target"]

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [7]:
california["feature_names"]

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [3]:
california.data[:5]

array([[ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00,
         1.02380952e+00,  3.22000000e+02,  2.55555556e+00,
         3.78800000e+01, -1.22230000e+02],
       [ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,
         9.71880492e-01,  2.40100000e+03,  2.10984183e+00,
         3.78600000e+01, -1.22220000e+02],
       [ 7.25740000e+00,  5.20000000e+01,  8.28813559e+00,
         1.07344633e+00,  4.96000000e+02,  2.80225989e+00,
         3.78500000e+01, -1.22240000e+02],
       [ 5.64310000e+00,  5.20000000e+01,  5.81735160e+00,
         1.07305936e+00,  5.58000000e+02,  2.54794521e+00,
         3.78500000e+01, -1.22250000e+02],
       [ 3.84620000e+00,  5.20000000e+01,  6.28185328e+00,
         1.08108108e+00,  5.65000000e+02,  2.18146718e+00,
         3.78500000e+01, -1.22250000e+02]])

In [4]:
california.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [5]:
california.target_names

['MedHouseVal']

In [8]:
df = pd.DataFrame(california.data)

In [9]:
df.columns = california.feature_names

In [10]:
df['MedHouseVal'] = california.target 

In [9]:
df 

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

In [11]:
df.values


array([[   8.3252    ,   41.        ,    6.98412698, ...,   37.88      ,
        -122.23      ,    4.526     ],
       [   8.3014    ,   21.        ,    6.23813708, ...,   37.86      ,
        -122.22      ,    3.585     ],
       [   7.2574    ,   52.        ,    8.28813559, ...,   37.85      ,
        -122.24      ,    3.521     ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,   39.43      ,
        -121.22      ,    0.923     ],
       [   1.8672    ,   18.        ,    5.32951289, ...,   39.43      ,
        -121.32      ,    0.847     ],
       [   2.3886    ,   16.        ,    5.25471698, ...,   39.37      ,
        -121.24      ,    0.894     ]])

In [14]:
X = pd.DataFrame(california.data, columns=california.feature_names)
y = pd.DataFrame(california.target, columns=["Median_House_Value"])


In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [16]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
df.values


array([[   8.3252    ,   41.        ,    6.98412698, ...,   37.88      ,
        -122.23      ,    4.526     ],
       [   8.3014    ,   21.        ,    6.23813708, ...,   37.86      ,
        -122.22      ,    3.585     ],
       [   7.2574    ,   52.        ,    8.28813559, ...,   37.85      ,
        -122.24      ,    3.521     ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,   39.43      ,
        -121.22      ,    0.923     ],
       [   1.8672    ,   18.        ,    5.32951289, ...,   39.43      ,
        -121.32      ,    0.847     ],
       [   2.3886    ,   16.        ,    5.25471698, ...,   39.37      ,
        -121.24      ,    0.894     ]])

In [20]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


In [21]:
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train.values.ravel())
#the ravel funtion in y_train is used to convert 2D array into 1D array as model is expecting 1D array


RandomForestRegressor(random_state=42)

In [23]:
y_train.values.shape

(16512, 1)

In [24]:
y_pred_rf = rf_model.predict(X_test_scaled)

In [25]:
print("Random Forest Regression Metrics:")
print(f"MAE: {mean_absolute_error(y_test, y_pred_rf)}")#as less the value the better the model
print(f"MSE: {mean_squared_error(y_test, y_pred_rf)}")#as less the value the better the model
print(f"R2 Score: {r2_score(y_test, y_pred_rf)}")#it veries from 0-1 0 means bad 1 means good

Random Forest Regression Metrics:
MAE: 0.3274252027374032
MSE: 0.255169737347244
R2 Score: 0.8052747336256919


In [26]:
with open("random_forest_model.pkl", "wb") as f:
    pickle.dump(rf_model, f)# it will convert the file into binary.

In [28]:
import tensorflow as tf
from tensorflow import keras

# Build the model
dl_model = keras.Sequential([
    keras.layers.Dense(64, activation="relu", input_shape=(X_train_scaled.shape[1],)),
    keras.layers.Dense(32, activation="relu"),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dense(1)  # Output layer for regression
])# dense means all the node of one layer to connect to all the other layers

In [29]:
dl_model.compile(optimizer="adam", loss="mse", metrics=["mae"])

In [30]:
dl_model.fit(X_train_scaled, y_train, validation_data=(X_test_scaled, y_test), epochs=50, batch_size=00)


Epoch 1/50


516/516 [==============================] - 3s 2ms/step - loss: 0.8457 - mae: 0.5972 - val_loss: 0.4176 - val_mae: 0.4503
Epoch 2/50
516/516 [==============================] - 1s 2ms/step - loss: 0.3865 - mae: 0.4396 - val_loss: 0.3725 - val_mae: 0.4281
Epoch 3/50
516/516 [==============================] - 1s 2ms/step - loss: 0.3651 - mae: 0.4254 - val_loss: 0.3616 - val_mae: 0.4195
Epoch 4/50
516/516 [==============================] - 1s 2ms/step - loss: 0.3475 - mae: 0.4123 - val_loss: 0.3661 - val_mae: 0.4411
Epoch 5/50
516/516 [==============================] - 1s 2ms/step - loss: 0.3477 - mae: 0.4030 - val_loss: 0.3459 - val_mae: 0.4103
Epoch 6/50
516/516 [==============================] - 1s 2ms/step - loss: 0.3215 - mae: 0.3947 - val_loss: 0.3280 - val_mae: 0.4053
Epoch 7/50
516/516 [==============================] - 1s 2ms/step - loss: 0.3109 - mae: 0.3875 - val_loss: 0.3186 - val_mae: 0.3954
Epoch 8/50
516/516 [==============================] - 1s 2ms/step - loss: 

In [22]:
dl_model.save("deep_learning_model.h5")


C:\Users\1034590\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [23]:
with open("random_forest_model.pkl", "rb") as f:
    loaded_rf_model = pickle.load(f)


y_pred_loaded_rf = loaded_rf_model.predict(X_test_scaled)
print(f"Loaded RF Model R2 Score: {r2_score(y_test, y_pred_loaded_rf)}")



Loaded RF Model R2 Score: 0.8052747336256919


In [24]:
loaded_dl_model = keras.models.load_model("deep_learning_model.h5")


y_pred_loaded_dl = loaded_dl_model.predict(X_test_scaled)
print(f"Loaded DL Model MSE: {r2_score(y_test, y_pred_loaded_dl)}")

129/129 [==============================] - 0s 891us/step
Loaded DL Model MSE: 0.7882409236865926
